doThing('value', (err, result) => {
  if (err) {
    // handle error here
    console.log(err);
  } else {
    // handle success here
    console.log(result);
  }
})
